return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 31,
  properties = {
    ["music"] = "field_jarona",
    ["name"] = "Wheat Field - \"Barracks\""
  },
  tilesets = {
    {
      name = "farm_world",
      firstgid = 1,
      filename = "../../../../tilesets/farm_world.tsx",
      exportfilename = "../../../../tilesets/farm_world.lua"
    },
    {
      name = "farm_world_extras",
      firstgid = 101,
      filename = "../../../../tilesets/farm_world_extras.tsx",
      exportfilename = "../../../../tilesets/farm_world_extras.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 6,
      name = "Tile Layer 3",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 102, 102, 101, 9, 9, 8, 9, 9, 8, 9, 8, 102, 101, 102, 105,
        101, 104, 0, 9, 7, 7, 7, 7, 7, 7, 7, 7, 8, 101, 104, 105,
        103, 101, 101, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 105, 0, 102,
        101, 102, 0, 19, 17, 18, 18, 17, 17, 18, 17, 17, 20, 0, 103, 103,
        0, 104, 0, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 0, 101, 104,
        103, 102, 12, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 13, 3, 11,
        16, 16, 16, 16, 6, 6, 5, 5, 5, 5, 5, 6, 15, 16, 15, 16,
        15, 16, 16, 16, 16, 15, 15, 15, 16, 15, 16, 16, 16, 16, 16, 16,
        15, 16, 15, 15, 16, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16,
        11, 13, 14, 1, 1, 4, 13, 14, 3, 2, 3, 12, 1, 13, 14, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 200,
          width = 320,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 114,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm3",
            ["marker"] = "to_couch"
          }
        },
        {
          id = 12,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["talk"] = true,
            ["talksprite"] = "talk",
            ["text1_1"] = "* Welcome to the BARRACKS room,[wait:5] soldier!",
            ["text1_2"] = "* Me and the company are resting up so we can defeat the GARDNER,[wait:5] soldier!",
            ["text1_3"] = "* We won't let him take our life force,[wait:5] soldier!",
            ["text2_1"] = "* What?[wait:5] No,[wait:5] we're not just \"chilling here on a couch\" dude.",
            ["text2_2"] = "* ...[wait:5]soldier.",
            ["text3_1"] = "* ...[wait:5]soldier."
          }
        },
        {
          id = 13,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["talk"] = true,
            ["talksprite"] = "talk",
            ["text1_1"] = "* GARDNER may have harvested many of my fellow Colonels...",
            ["text1_2"] = "* He MAY be exponentially growing in power at an alarming rate...",
            ["text1_3"] = "* And he MAY be truly impossible to vanquish...",
            ["text1_4"] = "* But I still have HOPE,[wait:5] lieutenant !!",
            ["text1_5"] = "* Hope,[wait:5] that the power of [color:lime]FRIENDSHIP[color:reset] will win the day !!",
            ["text1_6"] = "* That,[wait:5] and overwhelming firepower.",
            ["text2_1"] = "* Yeah maybe it's just firepower"
          }
        },
        {
          id = 22,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/farm_world.barracks",
            ["flag"] = "barracks",
            ["once"] = true
          }
        },
        {
          id = 25,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 300,
          y = 220,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["heals"] = true,
            ["marker"] = "spawn",
            ["text1"] = "* (Seeing people lounge around and avoid responsibilities...)",
            ["text2"] = "* (It almost brings a tear to your eye.[wait:5] It also fills you with a certain power...)",
            ["text_once"] = true
          }
        },
        {
          id = 16,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 120,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 17,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 20,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 18,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 120,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 21,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 120,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 27,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 160,
          width = 20,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 5,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        102, 103, 103, 104, 101, 105, 101, 102, 102, 102, 102, 105, 104, 104, 104, 102,
        101, 105, 101, 104, 105, 103, 104, 104, 101, 104, 102, 101, 103, 104, 103, 105,
        101, 105, 102, 101, 104, 101, 103, 105, 103, 104, 103, 101, 103, 101, 104, 104
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 640,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 200,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 80,
          width = 400,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 120,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 200,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 40,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 160,
          width = 40,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "to_farm3",
          type = "",
          shape = "point",
          x = 40,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "grace_spawn",
          type = "",
          shape = "point",
          x = 540,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "grace_leaf",
          type = "",
          shape = "point",
          x = 690,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "spawn",
          type = "",
          shape = "point",
          x = 240,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 28,
          name = "toggle",
          type = "",
          shape = "point",
          x = 690,
          y = 180,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "barracks",
            ["inverted"] = true,
            ["target"] = { id = 22 }
          }
        }
      }
    }
  }
}
