return {
    barracks2 = function(cutscene, event)
        local colonel = cutscene:getCharacter("colonel", 2)
        local colonel2 = cutscene:getCharacter("colonel", 1)
        local colonel3 = cutscene:getCharacter("colonel", 3)
        local colonel4 = cutscene:getCharacter("colonel", 4)
        local colonel5 = cutscene:getCharacter("colonel", 5)
        local vess = cutscene:getCharacter("vess")
        local options = {
            ["talk"] = true;
        }
        cutscene:setSpeaker(colonel, true)
        cutscene:setTextboxTop(false)
        cutscene:setSprite(colonel, "talk", 1/6)
        if event.interact_count == 1 then
            cutscene:text("* Greetings,[wait: 5] lieutenant !!", nil, colonel, options)
            cutscene:text("* FANTASTIC job evading the GARDNER !!", nil, colonel, options)
            cutscene:text("* Now we've pushed into the GARDEN !![wait:5] Operation Stalwart Kernel is complete...", nil, colonel, options)
            cutscene:text("* [color:lime]FRIENDSHIP[color:reset] can truly bring us to victory !!", nil, colonel, options)
            cutscene:text("* That being said,[wait:5] this was as far as HQ wanted us to push for now.", nil, colonel, options)
            cutscene:text("* That means we won't be going ahead with you,[wait:5] lieutenant.", nil, colonel, options)
            cutscene:text("* So,[wait:5] that means this is goodbye...", nil, colonel, options)
            cutscene:wait(1)
            cutscene:text("* UNLESS !!", nil, colonel, options)
            cutscene:text("* UNLESS !!", nil, colonel, options)
            cutscene:text("* You wanna go and PATROL the FIELD of WHEAT and CORN...", nil, colonel, options)
            cutscene:text("* In which case,[wait:5] let me know anytime.", nil, colonel, options)
            cutscene:text("* The squad and I will be happy to accompany you.", nil, colonel, options)
        elseif event.interact_count >= 2 then
            cutscene:text("* Well lieutenant?[wait:5] What'll it be?")
            local choice = cutscene:choicer({"Yes \npatrol", "No \npatrol"})
            if choice == 1 then
                Game:setFlag("leading_colonels_squad", true)
                cutscene:text("* Alright lieutenant !!!!!!!!!")
                cutscene:text("* Lead the way !!")
                colonel:convertToFollower()
                colonel2:convertToFollower()
                colonel3:convertToFollower()
                colonel4:convertToFollower()
                colonel5:convertToFollower()
                Game:addFollower(colonel)
                Game:addFollower(colonel2)
                Game:addFollower(colonel3)
                Game:addFollower(colonel4)
                Game:addFollower(colonel5)
            else 
                cutscene:text("* Alrighty lieutenant.[wait:5] We'll be here.")
            end
        end
        cutscene:setSprite(colonel, "idle") 
    end;
    barracks2_partydisband = function(cutscene, event)
        local colonel = cutscene:getCharacter("colonel", 2)
        local colonel2 = cutscene:getCharacter("colonel", 1)
        local colonel3 = cutscene:getCharacter("colonel", 3)
        local colonel4 = cutscene:getCharacter("colonel", 4)
        local colonel5 = cutscene:getCharacter("colonel", 5)
        local vess = cutscene:getCharacter("vess")
        local options = {
            ["talk"] = true;
        }
        if Game:getFlag("leading_colonels_squad", true) then
            local mainColonel = Game.world.followers[1]
            local vessPos = vess:getPosition() --Lmao
            local followers = Game.world.followers
            cutscene:setTextboxTop(true)
            cutscene:setSpeaker(mainColonel, true)
            cutscene:setSprite(mainColonel, "talk", 1/6)
            cutscene:text("* We can't go any further,[wait:5] lieutenant.")
            cutscene:text("* Good luck in the GARDEN...")
            cutscene:text("* ...and give GARDNER hell !!")
            -- some sort of cheer sound effect
            cutscene:wait(cutscene:fadeOut(1))
            Assets.playSound("item")
            cutscene:setSprite(mainColonel, "idle")
            --Game.world:removeFollower(colonel, 2)
            --Game.world:removeFollower(colonel2, 1)
            --Game.world:removeFollower(colonel3, 3)
            --Game.world:removeFollower(colonel4, 4)
            --Game.world:removeFollower(colonel5, 5) --i probably shouldnt have added the numbers here
            for _, follower in pairs(followers) do
                Game.world:removeFollower(follower)
                follower:remove()
            end
            for _, follower in pairs(followers) do
                Game.world:removeFollower(follower)
                follower:remove()
            end
            for _, follower in pairs(followers) do --dude this is disgusting
                Game.world:removeFollower(follower)
                follower:remove()
            end
            Game:setFlag("leading_colonels_squad", false)
            Game.world:loadMap("chapter1/farm_world/garden1")
            cutscene:wait(0.5)
            cutscene:look("vess", "up")
            cutscene:fadeIn(1)
        else
            return
        end
    end;
    ofer_intro = function(cutscene, event)
        local grace = cutscene:spawnNPC("grace", 860, 420)
        local vess = cutscene:getCharacter("vess")
        local door = Game.world:getEvent(6)
        local tofer = cutscene:spawnNPC("tofer", 1200, 280)
        cutscene:look(grace, "up")
        cutscene:detachCamera()
        cutscene:wait(cutscene:panTo(800, Game.world.camera.y, 2))
        cutscene:wait(cutscene:walkTo(vess, "vess_target", 3))
        cutscene:wait(2)
        cutscene:look(grace, "left")
        cutscene:wait(1)
        cutscene:setSpeaker(grace)
        cutscene:text("[face:brow, -19, -13]* Oh,[wait:5] hey.")
        cutscene:look(grace, "up")
        cutscene:wait(2)
        cutscene:look(grace, "left")
        cutscene:text("[face:consider, -19, -13]* Uhhh...[wait:5] why the $$$$ is \nthere a giant shed here.")
        cutscene:wait(1)
        cutscene:text("[face:sus, -19, -13]* Wait,[wait:5] no,[wait:5] I hate you.")
        cutscene:text("[face:pissed, -19, -13]* Stop pondering with me.")
        cutscene:look(grace, "up")
        cutscene:look(vess, "up")
        cutscene:wait(2)
        cutscene:look(grace, "left")
        cutscene:text("[face:sus, -19, -13]* But,[wait:5] like,[wait:5] I don't \nknow...")
        cutscene:look(vess, "right")
        cutscene:wait(1)
        cutscene:text("[face:sus, -19, -13][next]* It's kinda hard to keep \nhating ")
        Assets.playSound("locker")
        door:setColor(1, 1, 1, 0)
        cutscene:wait(0.2)
        cutscene:setSprite(grace, "fall")
        cutscene:shakeCharacter(grace)
        Assets.playSound("grace_surprise")
        cutscene:walkTo(vess, "vess_walkback", 0.2, "right", true)
        cutscene:wait(1.5)
        cutscene:resetSprite(grace)
        cutscene:look(vess, "up")
        cutscene:look(grace, "up")
        cutscene:wait(2)
        cutscene:wait(cutscene:panTo(800, 240, 2))
        cutscene:wait(1)
        cutscene:setSpeaker(tofer)
        cutscene:text("* Hey,[wait:5] hey,[wait:5] hey!")
        cutscene:setSpeaker(grace)
        cutscene:text("[face:nervous, -19, -13]* UHHHHH...")
        Game.world.music:play("tofer")
        cutscene:wait(1.2) -- Intro of this song is 2 seconds on the dot. Thank god
        Assets.playSound("drive")
        cutscene:setAnimation(tofer, "cycle")
        cutscene:wait(cutscene:slideTo(tofer, "tofer_slide", 0.8))
        tofer:explode(0, 0, true)
        cutscene:wait(1)
        cutscene:setSpeaker(tofer)
        cutscene:text("* [sound:tofer_checkit]Check it!")
        cutscene:wait(0.5)
        cutscene:look(grace, "left")
        cutscene:wait(1)
        cutscene:look(grace, "up")
        cutscene:wait(0.5)
        cutscene:setSpeaker(grace)
        cutscene:text("[face:wtf, -19, -13]* Who the $$$$ are you.")
        cutscene:setSpeaker(tofer)
        cutscene:text("* Heh.[wait:5] It's me,[wait:5] Tofer!")
        cutscene:text("* Only the COOLEST CARROT in the garden.")
        cutscene:setSpeaker(grace)
        cutscene:text("[face:munch, -19, -13]* ...")
        cutscene:setSpeaker(tofer)
        cutscene:text("* Wanna know how cool I am ??!?")
        cutscene:setSpeaker(grace)
        cutscene:text("[face:sus, -19, -13][next]* Not really..")
        cutscene:setSpeaker(tofer)
        cutscene:text("* ONE TIME,[wait:5] while I was skating!")
        cutscene:text("* Someone fell and broke their ribs.")
        cutscene:text("* Get it?")
        cutscene:wait(1)
        cutscene:setSpeaker(grace)
        cutscene:text("[face:consider, -19, -13]* ...")
        cutscene:text("[face:brow, -19, -13]* ...")
        cutscene:setSpeaker(tofer)
        cutscene:text("* I gave them snare ribs![wait:5] [sound:tofer_checkit]:joy:")
    end;
}