return {
    start_day = function(cutscene, event)
        --cutscene:text("* (Start the day?)")
        local start = cutscene:textChoicer("* (Start the day?)", {"Yes", "Noooo"})

        if start == 1 then
            --cutscene:text("* (...)")
            --cutscene:text("* (...[wait:5]we haven't implemented\nthat yet.)")
            Game:setFlag("start_cutscene_active", true) --prevents premature room transitions
            cutscene:wait(cutscene:fadeOut(3))
            cutscene:wait(Game.world:mapTransition("chapter1/rural_mainstreet"))
            local music = Music()
            music:play("start")
            music:setLooping(false)
            cutscene:wait(cutscene:fadeIn(1))
            cutscene:wait(cutscene:walkTo("vess", "vess_target_start", 41, "up")) --41, top of mainstreet
            Game:setFlag("start_cutscene_active", false)
            --cutscene:wait(Game.world:mapTransition("chapter1/rural_school"))
            cutscene:wait(0.5)
            Game:setFlag("start_cutscene_active", true)
            cutscene:wait(cutscene:walkTo("vess", "vess_target_start", 4, "up")) --school door
            Game:setFlag("start_cutscene_active", false)
            cutscene:wait(1)
            Game:setFlag("start_cutscene_active", true)
            cutscene:wait(cutscene:walkTo("vess", "vess_target_start", 4, "up")) --top of hallway
            cutscene:wait(cutscene:walkTo("vess", "vess_target_start2", 4, "right")) --right side
            cutscene:walkTo("vess", "vess_target_start3", 4.25, "up")
            cutscene:wait(cutscene:fadeOut(4))
            
            music:stop()
            Game.world:loadMap("chapter1/rural_classroom")
            cutscene:wait(3)
            
            
            cutscene:text("* (All according[sound:bageldefeat] to[next]")
            cutscene:text("* [wave][style:GONER](All according to plant!)")
            cutscene:wait(cutscene:fadeIn(1))
            cutscene:text("* [wave](oh, you're stuck in the wall...)")
            cutscene:text("* [wave](oh[wait:5].[wait:5].[wait:5].)")
            cutscene:wait(Game.world:mapTransition("chapter1/rural_school"))
            Game:setFlag("start_cutscene_active", false)
            Assets.playSound("egg")

            --Game.world:startCutscene("chapter1/rural", "school")
        else
            --cutscene:text("* (Then,[wait:5] the [color:pink][style:GONER]LARPERS' RUNE[color:reset][style:none][wait:5] will\nbe waiting.)")
            cutscene:text("* (Then,[wait:5] it will be waiting.)")
        end
    end;

    test_school = function(cutscene)
        --cutscene:text("* (Watch the school cutscene \nso far?)")
        local start = cutscene:textChoicer("* (Watch the school cutscene \nso far?)", {"Yes", "Noooo"})

        if start == 1 then
            --cutscene:wait(cutscene:fadeOut(4))
            Assets.playSound("locker")
            cutscene:wait(cutscene:fadeOut(0))
            Game.world.music:stop()
            Game.world:loadMap("chapter1/rural_classroom")
            cutscene:wait(1)

            --cutscene setup
            local walrus = cutscene:getCharacter("walrus")
            local blunderbuss = cutscene:getCharacter("blunderbuss")
            local yoori = cutscene:getCharacter("yoori")
            local handle = cutscene:getCharacter("handle")
            local glaggle = cutscene:getCharacter("glaggle")
            local starwalker = cutscene:getCharacter("starwalker")
            local vess = cutscene:getCharacter("vess")
            local grace = cutscene:getCharacter("grace_lw")
            local tundra = cutscene:getCharacter("tundra_lw")

            cutscene:setSprite(handle, "handle_up")
            cutscene:setSprite(tundra, "up_1")
            cutscene:look(grace, "up")
            cutscene:slideTo(vess, "vess_outbound", 0.1)

            cutscene:wait(3)
            
            cutscene:text("* ...and that's why I prefer the original game.")
            cutscene:text("* Mods just can't beat a classic[wait:5] (haha),[wait:5] well-tailored gaming experience!")

            --cutscene:wait(2)
            Assets.playSound("noise")
            cutscene:fadeIn(0)

            cutscene:setSpeaker(handle)
            cutscene:wait(2)
            cutscene:setSprite(handle, "handle_right")
            cutscene:text("* Am I right,[wait:5] or am I right,[wait:5] Glaggle?")
            cutscene:setSpeaker(glaggle)
            cutscene:wait(1)
            cutscene:text("* Dude.[wait:5] I don't care.")
            Game.world.music:play("class2")
            cutscene:setSprite(handle, "handle_up")
            cutscene:wait(3)
            cutscene:setSpeaker(yoori)
            cutscene:text("[voice:none][sound:yoori]* I love books.")
            cutscene:setSpeaker(tundra)
            cutscene:setTextboxTop(true)
            cutscene:text("* Yo,[wait:5] Starwalker,[wait:5] are you coming to church tomorrow?")
            cutscene:setSpeaker(grace)
            cutscene:text("[face:consider, -19, -13]* (Huh.[wait:5] She goes to \nchurch...)")
            cutscene:setSpeaker(starwalker)
            cutscene:text("* Yeah.")
            cutscene:text("* By the way,[wait:5] I like your [color:yellow]fit[color:reset].")
            cutscene:text("* Your sneaks are[wait:5] nice[wait:5] [color:yellow]and[color:reset] original[wait:5]    .")
            cutscene:setSpeaker(tundra)
            cutscene:text("* Ahaha,[wait:5] thanks!")
            cutscene:setSpeaker(grace)
            cutscene:text("[face:nervous, -19, -13]* (...)")
            cutscene:look(grace, "right")
            cutscene:text("[face:consider, -19, -13]* Uhhhhhhhh,[wait:5] Tundra.[wait:5]")
            cutscene:text("[face:snark, -19, -13]* I,[wait:5] uh,[wait:5] also like your,[wait:5] \nuh....")
            cutscene:look(grace, "up")
            cutscene:setSpeaker(yoori)
            cutscene:setTextboxTop(false)
            cutscene:text("[voice:none][sound:yoori]* I love books!")
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* HEH.[wait:5] CAN'T WAIT TO PICK UP CHICKZ AT THE FESTIVAL.")
            cutscene:text("* WITH MY BESTFRIEND.[wait:5] WALRUS.")
            cutscene:setSpeaker(handle)
            cutscene:setSprite(handle, "handle_right")
            cutscene:text("* (Haha),[wait:5] heck yeah![wait:5] My man!")
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* ...")
            cutscene:text("* ...")
            cutscene:text("* DUDE I WASN'T $$$$ING TALKING \nTO YOU.")
            cutscene:text("* I WAS TALKING TO WALRUS.")
            cutscene:setSpeaker(walrus)
            --cutscene:text("* Yeah,[wait:5] man. [wait:5] He was talking to me bro watch out.")
            cutscene:text("* Yeah,[wait:5] man.")
            cutscene:setSprite(handle, "handle_up")
            cutscene:setSpeaker(glaggle)
            cutscene:text("* Dude.[wait:5] You guys don't think you're being a little rude?")
            cutscene:setSpeaker(yoori)
            cutscene:text("[voice:none][sound:yoori][next]* I love reading [sound:yoori]books![wait:5] \n[sound:yoori]Especially the")
            cutscene:setSpeaker(glaggle)
            cutscene:text("* Dude.[wait:5] We get it, Yoori.[wait:5] Shut that $$!$ up.")
            cutscene:wait(3)
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* HEY.")
            cutscene:text("* WALRUS.")
            cutscene:wait(2)
            cutscene:text("* WALRUS.")
            cutscene:setSpeaker(walrus)
            cutscene:text("* Yeah,[wait:5] man.")
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* ISN'T THAT LIDDLE GRAY PERSON JUST SO WEIRD.")
            cutscene:text("* RIGHT,[wait:5] WALRUS?")
            cutscene:setSpeaker(walrus)
            cutscene:text("* Yeah,[wait:5] man.")
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* HEH.[wait:5] YAHHH.")
            cutscene:text("* HEH.[wait:5] I BET EVEN HANDLE THINKS \nSO TOO.")
            cutscene:setSprite(handle, "handle_right")
            cutscene:setSpeaker(handle)
            cutscene:text("* (Haha),[wait:5] I sure do![wait:5] Right on,[wait:5] Blunderbuss!")
            cutscene:setSpeaker(walrus)
            cutscene:text("* Yeah,[wait:5] man.")
            cutscene:setSprite(handle, "handle_up")
            cutscene:setSpeaker(glaggle)
            cutscene:text("* Dude.[wait:5] You guys are being so rude.")
            cutscene:text("* ...[wait:5]but you're totally right.[wait:5] That gray person is so creepy.")
            cutscene:text("* I heard that they eat hay and,[wait:5] shudders,[wait:5] walk to school...")
            cutscene:setSpeaker(handle)
            cutscene:setSprite(handle, "handle_right")
            cutscene:text("* I heard they[wait:5] (haha)[wait:5] sleep out \nof a car...[wait:5] and use spray-on shampoo!")
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* HEH.[wait:5] YAHHH.")
            cutscene:setSprite(handle, "handle_up")
            cutscene:wait(2)
            cutscene:text("* WALRUS.")
            cutscene:setSpeaker(walrus)
            cutscene:text("* Yeah,[wait:5] man.")
            cutscene:setSpeaker(blunderbuss)
            cutscene:text("* WATCH THIS.")
            cutscene:text("* HEH.[wait:5] THAT GRAY PERSON SURE IS WEIRD.[wait:5] RIGHT,[wait:5] GRACE?")
            cutscene:wait(2)
            cutscene:text("* HEH.[wait:5] RIGHT,[wait:5] GRACE?")
            cutscene:setSpeaker(grace)
            cutscene:wait(1)
            cutscene:setTextboxTop(true)
            cutscene:text("[face:brow, -19, -13]* Oh.[wait:5] Uh,[wait:5] sure.")
            cutscene:setSpeaker(blunderbuss)
            cutscene:setTextboxTop(false)
            cutscene:text("* HEH.[wait:5] RIGHT.")
            cutscene:text("* ...")
            cutscene:text("* ...[wait:5]YOU GOING TO THE FESTIVAL,[wait:5] SWEETCHEEK?")
            cutscene:setSpeaker(grace)
            cutscene:setTextboxTop(true)
            cutscene:text("[face:sus, -19, -13]* Uh,[wait:5] no.")
            cutscene:text("[face:consider, -19, -13]* (Not with you,[wait:5] anyway...)")
            cutscene:setSpeaker(blunderbuss)
            cutscene:setTextboxTop(false)
            cutscene:text("* HEH.[wait:5] YOU AGREE WITH ME TOO,[wait:5] TUNDRA?")
            cutscene:setSpeaker(tundra)
            cutscene:setTextboxTop(true)
            cutscene:text("* Nah.[wait:5] Actually,[wait:5] I think...")
            Game.world.music:stop()
            cutscene:look(vess, "down")
            vess:setPosition(140, 188)
            Assets.playSound("dooropen")
            cutscene:wait(1/8)
            Assets.playSound("doorclose")


            cutscene:wait(3)
            
            cutscene:text("* (All according[sound:bageldefeat] to[next]")
            cutscene:text("* [wave][style:GONER](All according to plant!)")



            Game:setFlag("start_cutscene_active", false)
        else
            cutscene:text("* (Then,[wait:5] it will be waiting.)")
        end
    end;

    school = function (cutscene)
        
    end;
}