return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 40,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 111,
  properties = {
    ["name"] = "Test Map - Room 1"
  },
  tilesets = {
    {
      name = "castle",
      firstgid = 1,
      filename = "../tilesets/castle.tsx",
      exportfilename = "../tilesets/castle.lua"
    },
    {
      name = "rural_buildings",
      firstgid = 41,
      filename = "../tilesets/rural_buildings.tsx",
      exportfilename = "../tilesets/rural_buildings.lua"
    },
    {
      name = "farm_world_extras",
      firstgid = 73,
      filename = "../tilesets/farm_world_extras.tsx",
      exportfilename = "../tilesets/farm_world_extras.lua"
    },
    {
      name = "GONER",
      firstgid = 101,
      filename = "../tilesets/GONER.tsx",
      exportfilename = "../tilesets/GONER.lua"
    },
    {
      name = "intro",
      firstgid = 126,
      filename = "../tilesets/intro.tsx",
      exportfilename = "../tilesets/intro.lua"
    },
    {
      name = "farm_world",
      firstgid = 129,
      filename = "../tilesets/farm_world.tsx",
      exportfilename = "../tilesets/farm_world.lua"
    },
    {
      name = "garden",
      firstgid = 229,
      filename = "../tilesets/garden.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 40,
      id = 1,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 130, 0, 0, 0, 0, 130, 0, 0, 0, 0, 0, 0, 0, 140, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 140, 0, 0, 0, 0, 140, 0, 142, 0, 0, 0, 0, 141, 0, 0, 0,
        0, 0, 130, 0, 131, 0, 0, 0, 0, 0, 0, 0, 0, 142, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 130, 0, 0, 0, 0, 0, 0, 0, 0, 0, 137, 137, 136, 136, 0, 130,
        0, 0, 0, 0, 0, 0, 0, 0, 140, 131, 131, 130, 0, 137, 135, 135, 135, 135, 136, 0,
        0, 0, 249, 234, 234, 234, 233, 235, 233, 150, 149, 150, 136, 135, 135, 135, 135, 135, 135, 0,
        0, 0, 234, 233, 234, 233, 233, 233, 234, 233, 233, 234, 133, 145, 145, 145, 146, 145, 146, 134,
        0, 0, 233, 233, 234, 235, 234, 233, 235, 233, 233, 133, 133, 133, 133, 134, 133, 134, 134, 133,
        0, 0, 233, 233, 235, 234, 233, 233, 234, 233, 150, 133, 135, 135, 135, 135, 135, 135, 135, 0,
        0, 0, 235, 233, 233, 233, 247, 247, 247, 247, 0, 0, 0, 135, 135, 135, 135, 135, 135, 0,
        249, 233, 233, 235, 233, 233, 233, 233, 257, 257, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        233, 235, 233, 234, 234, 233, 233, 233, 267, 267, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        237, 237, 237, 237, 237, 237, 237, 237, 277, 277, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        247, 247, 247, 247, 247, 247, 247, 247, 287, 287, 0, 0, 0, 0, 0, 0, 131, 0, 0, 0,
        257, 257, 257, 257, 257, 257, 257, 257, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 17, 9, 17, 17, 9, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 22, 13, 23, 23, 13, 23, 23, 23, 13, 23, 23, 13, 24, 0, 0, 0, 0, 0, 0,
        0, 22, 23, 23, 23, 23, 23, 21, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0, 0,
        0, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 0, 0, 0, 0, 0, 0,
        0, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 0, 0, 0, 0, 0, 0,
        0, 10, 11, 11, 101, 11, 11, 11, 11, 11, 11, 11, 11, 12, 0, 0, 0, 0, 0, 0,
        101, 101, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 7, 101, 7, 7, 101, 101,
        101, 101, 101, 11, 11, 11, 11, 11, 11, 11, 11, 11, 101, 101, 15, 15, 101, 101, 101, 101,
        0, 10, 11, 101, 11, 11, 11, 11, 11, 11, 11, 101, 101, 101, 0, 0, 0, 0, 0, 0,
        0, 14, 15, 15, 11, 11, 11, 11, 11, 11, 11, 101, 15, 16, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 14, 15, 11, 11, 11, 15, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        78, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 18, 19, 20, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 23, 24, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 22, 9, 24, 0,
        0, 0, 0, 0, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 0,
        0, 6, 7, 7, 7, 7, 11, 11, 11, 7, 7, 7, 7, 7, 7, 7, 11, 11, 12, 0,
        0, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 15, 15, 15, 16, 0,
        0, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 0, 0, 0, 0, 0, 0,
        0, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 0, 0, 0, 0, 0, 0,
        0, 11, 11, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 0, 0, 0, 0, 0, 0,
        0, 143, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 40,
      id = 2,
      name = "decal",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 30, 31, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 34, 35, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 80, 83, 0, 0, 0, 38, 39, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0,
        0, 84, 81, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0,
        0, 0, 0, 84, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0,
        0, 0, 81, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 0.5,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 720,
          width = 520,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 760,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 800,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 920,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 920,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 1000,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1040,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1320,
          width = 280,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1440,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 1560,
          width = 440,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1360,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 1320,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1040,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1000,
          width = 40,
          height = 360,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 920,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1080,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 1280,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1240,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 1280,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 1440,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 320,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 200,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 200,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 520,
          width = 320,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 400,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 400,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 360,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 200,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 160,
          width = 360,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 360,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 760,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_ladder",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 390,
          y = 760,
          width = 150,
          height = 430,
          rotation = 0,
          opacity = 1,
          gid = 64,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 1480,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "starwalker",
            ["text1_1"] = "* These [color:red]larpers[color:reset] are...",
            ["text1_2"] = "* Hey,[wait:5] uh...",
            ["text1_3"] = "* Is anyone going to do anything about the big ass [color:green][sound:QUADO]green[color:reset] couch in this room?",
            ["text1_4"] = "* Or like...[wait:5] [color:red]any[sound:ominous][color:reset] of the other $$!$ ??!?[sound:awkward]",
            ["text2_1"] = "* Guess[sound:QUADO] not. [sound:GPT]",
            ["text3_1"] = "* [color:yellow]...[sound:PREDICTIVE]"
          }
        },
        {
          id = 27,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 70,
          y = 940,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* Many things have changed in this testing area.[wait:5] Mostlys for the worse.",
            ["text2"] = "* Yet still,[wait:5] the immutable power of larpery steels within you."
          }
        },
        {
          id = 28,
          name = "squeak",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1240,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 840,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room2",
            ["marker"] = "entry"
          }
        },
        {
          id = 33,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 720,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "room1.wall",
            ["once"] = true
          }
        },
        {
          id = 35,
          name = "npc",
          type = "",
          shape = "point",
          x = 300,
          y = 800,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "wall",
            ["flagcheck"] = "wall_hit",
            ["text1"] = "* I Am the Wall Guardian.[wait:5]\n* This Wall is Off Limits for you\nno-good wall slammers."
          }
        },
        {
          id = 44,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 1320,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* This[sound:quato] is[sound:quato] the[sound:quato] coolest[sound:quato] wall[sound:quato] in[sound:quato] the[sound:quato] room[sound:quato].[wait:5]\n* Trade on [sound:GPT][color:green]Quado[sound:quato]\nQuado\nQuado\nQuado\nQuado\nQuado\nQuado\nQuado\nQuado"
          }
        },
        {
          id = 45,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 1480,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "kris",
            ["facing"] = "left",
            ["text1_1"] = "* Never mind dude.[wait:5] I don't even wanna be in your party anyway",
            ["text1_2"] = "* *Is not a tsundere*",
            ["text2_1"] = "* Stawp.[sound:farmerlaugh][wait:5] I'm not a tsundereeee",
            ["turn"] = true
          }
        },
        {
          id = 49,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 490,
          y = 1150,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "flight",
            ["text1_1"] = "* About time someone interacted with me.",
            ["text1_2"] = "* Don't take my lament the wrong way.[wait:5] I'm grateful![wait:5] It truly means a lot to me.",
            ["text2_1"] = "* Cherish this world,[wait:5] won't you?",
            ["text2_2"] = "* Soon,[wait:5] everything left of the original will be painted over anew...",
            ["text3_1"] = "* Don't you have anything better to do?"
          }
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 740,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 720,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "room1.grace_voice_test"
          }
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1470,
          width = 320,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 86,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "larpwalker",
            ["text1_1"] = "* [color:red]Larp[sound:DELTALARP_ch2]walker"
          }
        },
        {
          id = 57,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1390,
          width = 320,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Just a green couch in a green room.)"
          }
        },
        {
          id = 58,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 990,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "larpwalker",
            ["solid"] = false,
            ["text1_1"] = "* [color:red]Larp[sound:DELTALARP_ch7]walker"
          }
        },
        {
          id = 59,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 790,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "blunderbuss",
            ["cutscene"] = "chapter1/rural.test_school",
            ["solid"] = false
          }
        },
        {
          id = 60,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 190,
          y = 920,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "larpwalker",
            ["solid"] = false,
            ["text1_1"] = "* [color:red]Larp[sound:DELTALARP_ch4]walker"
          }
        },
        {
          id = 61,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 350,
          y = 840,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "larpwalker",
            ["solid"] = false,
            ["text1_1"] = "* [color:red]Larp[sound:DELTALARP_ch3]walker"
          }
        },
        {
          id = 62,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 960,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "larpwalker",
            ["solid"] = false,
            ["text1_1"] = "* [color:red]Larp[sound:DELTALARP_ch6]walker"
          }
        },
        {
          id = 63,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 1480,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "GONER_0",
            ["facing"] = "right",
            ["text1_1"] = "* Meet me...[wait:5] down the path to our south...",
            ["text2_1"] = "* Oh,[wait:5] Vess...[wait:5] Uhm,[wait:5] I mean,[wait:5] you can come too,[wait:5] I guess.[wait:5] Fahaha! ",
            ["text3_1"] = "* (They're silently sneering and jeering...)",
            ["turn"] = false
          }
        },
        {
          id = 65,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 1320,
          width = 200,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* Help"
          }
        },
        {
          id = 66,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 1080,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text"] = "* Help"
          }
        },
        {
          id = 70,
          name = "climbarea",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 360,
          width = 120,
          height = 360,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 720,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 75 }
          }
        },
        {
          id = 74,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 68 }
          }
        },
        {
          id = 88,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 720,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 86 }
          }
        },
        {
          id = 89,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 720,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 87 }
          }
        },
        {
          id = 90,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 660,
          y = 260,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "gardner",
            ["text1"] = "[face:smile]* Howdy!"
          }
        },
        {
          id = 91,
          name = "warpdoor",
          type = "",
          shape = "point",
          x = 140,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map1"] = "chapter1/farm_world/farm1",
            ["map2"] = "chapter1/farm_world/farm_gardner_test",
            ["map3"] = "chapter1/rural1",
            ["marker1"] = "spawn",
            ["marker2"] = "spawn",
            ["marker3"] = "spawn",
            ["name1"] = "Dark World",
            ["name2"] = "Gardner Chase",
            ["name3"] = "Start Day?",
            ["open"] = true
          }
        },
        {
          id = 92,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 850,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "starwalker",
            ["text1_1"] = "* Hey,[wait:5] so,[wait:5] I WAS a placeholder NPC in chapter1/farm_world/farm3...",
            ["text1_2"] = "* But,[wait:5] uh...[wait:5] I think I got fired.",
            ["text1_3"] = "* And,[wait:5] I mean...[wait:5] that's fine,[wait:5] I was going to quit soon anyway...",
            ["text1_4"] = "* But like...",
            ["text1_5"] = "* I didn't know getting fired meant hellfire.[wait:5] What the hell is this place man",
            ["text2_1"] = "* Never mind.[wait:5] Just heard about [color:green][sound:QUADO]QUADO[color:reset].",
            ["text2_2"] = "* trading rn[sound:wheredidtheyhidetheza]",
            ["text3_1"] = "* trading rn[sound:wheredidtheyhidetheza]"
          }
        },
        {
          id = 103,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 460,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "sofer",
            ["text1_1"] = "* Blood![wait:5] Blood![wait:5] Blood![wait:5]"
          }
        },
        {
          id = 104,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 30,
          y = 460,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "tofer",
            ["text1_1"] = "* Check it![sound:tofer_checkit]"
          }
        },
        {
          id = 105,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 1600,
          width = 78.667,
          height = 42.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm8",
            ["marker"] = "to_room1"
          }
        },
        {
          id = 107,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 70,
          y = 830,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "starwalker",
            ["text1_1"] = "* Hey,[wait:5] so,[wait:5] they fired me.[wait:5] Too.",
            ["text1_2"] = "* From chapter1/farm_world/garden_ladder3.",
            ["text2_1"] = "* I guess I was related to that other guy,[wait:5] after all...",
            ["text3_1"] = "* No,[wait:5] I will not be trading on [color:green]QUADO[color:reset][sound:QUADO] like these lowly simpletons.",
            ["text3_2"] = "* I have more...[wait:5] refined hobbies to indulge in instead.",
            ["text3_3"] = "* Hobbies that stimulate the mind,[wait:5] zah ha ha!",
            ["text4_1"] = "* WD [sound:wheredidtheyhidetheza]Gaster [sound:wheredidtheyhidetheza]Vecember [sound:wheredidtheyhidetheza]Holiday [sound:wheredidtheyhidetheza]Carol Rudy Knight Penumbra Ramb Eram Mancountry Image Friend Forgotten Man Last [sound:wheredidtheyhidetheza]Prophecy Northernlight Noelle Holiday Gaster Motif Girl Next Door DDLC [sound:wheredidtheyhidetheza]Theory"
          }
        },
        {
          id = 110,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 840,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "room_racing",
            ["marker"] = "spawn"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 68,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 69 }
          }
        },
        {
          id = 75,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 680,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 73 }
          }
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 700,
          width = 120,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 65,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 680,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 73 }
          }
        },
        {
          id = 87,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 680,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 73 }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 20,
          name = "spawn",
          type = "",
          shape = "point",
          x = 300,
          y = 890,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "entry",
          type = "",
          shape = "point",
          x = 760,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "susie_spawn",
          type = "",
          shape = "point",
          x = 690,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "susie_walk",
          type = "",
          shape = "point",
          x = 560,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "climb_exit",
          type = "",
          shape = "point",
          x = 460,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "climb_exit",
          type = "",
          shape = "point",
          x = 480,
          y = 810,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "to_farm8",
          type = "",
          shape = "point",
          x = 80,
          y = 1560,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "to_racing",
          type = "",
          shape = "point",
          x = 40,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
