return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 91,
  properties = {
    ["keepmusic"] = true,
    ["light"] = true,
    ["name"] = "Ruraltown - Classroom"
  },
  tilesets = {
    {
      name = "rural",
      firstgid = 1,
      filename = "../../tilesets/rural.tsx",
      exportfilename = "../../tilesets/rural.lua"
    },
    {
      name = "rural_buildings",
      firstgid = 101,
      filename = "../../tilesets/rural_buildings.tsx",
      exportfilename = "../../tilesets/rural_buildings.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 45, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 46, 0, 0,
        0, 0, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 0, 0,
        0, 0, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 61, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 62, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 160,
          width = 80,
          height = 120,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 130,
          width = 260,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 123,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 240,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 240,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 320,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 320,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 320,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 400,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 400,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 130,
          width = 260,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1_1"] = "* (Whiteboard.)",
            ["text1_2"] = "* (Hasn't been much to say about this thing...)",
            ["text2_1"] = "* (Not much to say about this thing.)"
          }
        },
        {
          id = 63,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 301.333,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "starwalker",
            ["text"] = "* What the hell is this class bro."
          }
        },
        {
          id = 64,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 220,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "yoori",
            ["text"] = "[voice:none][sound:yoori]* I love books!"
          }
        },
        {
          id = 66,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 330,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "blunderbuss",
            ["text"] = "* SWEETCHEEK."
          }
        },
        {
          id = 67,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 330,
          y = 300,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "glaggle",
            ["solid"] = false,
            ["text"] = "* Dude."
          }
        },
        {
          id = 68,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 203,
          y = 307.5,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "handle",
            ["text"] = "* Look at my encirclement!!!",
            ["turn"] = true
          }
        },
        {
          id = 69,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 330,
          y = 384,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "grace_lw",
            ["text"] = "[face:kawaii_neutral, -19, -13]* Uh,[wait:5] hey.",
            ["turn"] = true
          }
        },
        {
          id = 70,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 384,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "tundra_lw",
            ["text"] = "[face:smile_blush_blind, -23, -7]* Yo!",
            ["turn"] = true
          }
        },
        {
          id = 79,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 120,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "down",
            ["map"] = "chapter1/rural_school_inside",
            ["marker"] = "to_class",
            ["sound"] = "dooropen"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_floaters",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 65,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "walrus",
            ["solid"] = false,
            ["text"] = "* Yeah,[wait:5] man."
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "objects_test",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 120,
          width = 40,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 440,
          width = 560,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 120,
          width = 40,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 120,
          width = 380,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 210,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 20,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 210,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 210,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 290,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 290,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 290,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 370,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 370,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 370,
          width = 80,
          height = 10,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "spawn",
          type = "",
          shape = "point",
          x = 140,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "vess_outbound",
          type = "",
          shape = "point",
          x = 240,
          y = -70,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "front_of_door",
          type = "",
          shape = "point",
          x = 140,
          y = 180,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "vess_walk3",
          type = "",
          shape = "point",
          x = 220,
          y = 410,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "vess_walk",
          type = "",
          shape = "point",
          x = 140,
          y = 420,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "vess_walk2",
          type = "",
          shape = "point",
          x = 220,
          y = 420,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "blush_here",
          type = "",
          shape = "point",
          x = 140,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "to_hall",
          type = "",
          shape = "point",
          x = 140,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 71,
          name = "toggle",
          type = "",
          shape = "point",
          x = 440,
          y = -60,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "start_cutscene_active",
            ["target1"] = { id = 65 },
            ["target2"] = { id = 66 },
            ["target3"] = { id = 64 },
            ["target4"] = { id = 68 },
            ["target5"] = { id = 63 },
            ["target6"] = { id = 69 },
            ["target7"] = { id = 70 },
            ["target8"] = { id = 67 }
          }
        },
        {
          id = 78,
          name = "toggle",
          type = "",
          shape = "point",
          x = 30,
          y = -70,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "start_cutscene_active",
            ["inverted"] = true,
            ["target1"] = { id = 79 }
          }
        }
      }
    }
  }
}
