return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 31,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 10,
  nextobjectid = 165,
  properties = {
    ["light"] = true
  },
  tilesets = {
    {
      name = "rural",
      firstgid = 1,
      filename = "../../tilesets/rural.tsx",
      exportfilename = "../../tilesets/rural.lua"
    },
    {
      name = "rural_buildings",
      firstgid = 101,
      filename = "../../tilesets/rural_buildings.tsx",
      exportfilename = "../../tilesets/rural_buildings.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 24,
      height = 31,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 32, 33, 12, 12, 12, 12, 13, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 32, 33, 11, 21, 22, 22, 23, 13, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 33, 33, 11, 21, 22, 22, 23, 13, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 33, 33, 11, 21, 22, 22, 23, 13, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 33, 33, 11, 21, 22, 22, 23, 13, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 33, 33, 11, 21, 22, 22, 23, 13, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        32, 32, 32, 32, 33, 33, 11, 21, 22, 22, 23, 13, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        0, 0, 0, 32, 33, 33, 11, 21, 22, 22, 23, 13, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        0, 0, 0, 32, 33, 33, 24, 21, 22, 22, 23, 24, 33, 33, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
        0, 0, 0, 24, 24, 24, 24, 21, 22, 22, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        0, 0, 0, 24, 24, 41, 41, 15, 22, 22, 16, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
        0, 0, 0, 24, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        0, 0, 0, 24, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        0, 0, 0, 24, 24, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
        0, 0, 0, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 0,
          width = 40,
          height = 800,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = -40,
          width = 960,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 0,
          width = 40,
          height = 1240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1240,
          width = 960,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 1040,
          width = 40,
          height = 200,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 720,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 360,
          width = 496,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 40,
          width = 48,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 0,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 40,
          width = 48,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 0,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 950,
          y = 800,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 164,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 360,
          width = 100,
          height = 50,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/rural.enter_dw",
            ["once"] = false,
            ["setflag"] = "barn_opened",
            ["setvalue"] = false
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 800,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/rural_mainstreet",
            ["marker"] = "to_farm"
          }
        },
        {
          id = 16,
          name = "interactable",
          type = "",
          shape = "polygon",
          x = 80,
          y = 720,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 40 },
            { x = 0, y = 360 },
            { x = 880, y = 360 },
            { x = 880, y = 320 },
            { x = 40, y = 320 },
            { x = 40, y = 40 },
            { x = 120, y = 40 },
            { x = 120, y = 0 },
            { x = 160, y = 0 },
            { x = 160, y = -40 },
            { x = 200, y = -40 },
            { x = 200, y = -320 },
            { x = 40, y = 0 }
          },
          properties = {
            ["solid"] = true,
            ["text1_1"] = "* (This wheat...[wait:5] it doesn't look very harvested.)",
            ["text2_1"] = "* (It doesn't look very harvested.)"
          }
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 400,
          width = 720,
          height = 400,
          rotation = 0,
          opacity = 1,
          gid = 118,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 480,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 440,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 440,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 480,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 480,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 440,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 800,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 480,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 440,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 760,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 480,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 132,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 720,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 480,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 560,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 640,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {
            ["solid"] = true
          }
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 600,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 520,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 680,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 131,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 600,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/rural.barn_entrance",
            ["once"] = true
          }
        },
        {
          id = 142,
          name = "barndoor",
          type = "",
          shape = "rectangle",
          x = 266,
          y = 190,
          width = 188,
          height = 210,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 40,
          height = 280,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (This wheat...[wait:5] it doesn't look very harvested.)"
          }
        },
        {
          id = 155,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (This wheat...[wait:5] it doesn't look very harvested.)"
          }
        },
        {
          id = 156,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 720,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (This wheat...[wait:5] it doesn't look very harvested.)"
          }
        },
        {
          id = 158,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 760,
          width = 360,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (This wheat...[wait:5] it doesn't look very harvested.)"
          }
        },
        {
          id = 161,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 800,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/rural.barn_opened",
            ["once"] = false
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 24,
      height = 31,
      id = 6,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 131, 131, 131, 0, 0, 0, 0, 0, 0, 0, 0, 132, 131, 131, 0, 0, 0, 0, 0, 0, 0, 0,
        131, 131, 131, 131, 0, 0, 0, 0, 0, 0, 0, 0, 0, 132, 131, 131, 132, 0, 0, 0, 0, 0, 0, 0,
        131, 131, 131, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 132, 132, 132, 0, 0, 0, 0, 0, 0,
        131, 131, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 132, 132, 131, 131, 132, 0, 0, 0, 0,
        131, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131, 131, 131, 132, 132, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131, 131, 131, 131, 131, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 131, 132, 131, 132, 132, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 132, 132, 131, 131,
        114, 115, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 132,
        115, 114, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        117, 117, 117, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        114, 114, 117, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        114, 117, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        117, 117, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        114, 117, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        114, 114, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        114, 114, 117, 117, 115, 114, 115, 117, 115, 115, 114, 114, 115, 115, 114, 114, 114, 114, 117, 117, 117, 115, 114, 114,
        115, 114, 114, 114, 114, 117, 115, 115, 117, 114, 114, 115, 114, 114, 117, 117, 115, 114, 117, 115, 114, 114, 117, 114,
        115, 114, 114, 114, 117, 117, 114, 117, 114, 114, 114, 117, 117, 117, 115, 115, 117, 117, 117, 115, 115, 117, 114, 115,
        115, 115, 114, 115, 115, 114, 114, 115, 117, 117, 117, 114, 115, 115, 117, 114, 114, 115, 117, 117, 117, 117, 114, 114,
        117, 115, 117, 114, 115, 117, 115, 115, 117, 115, 115, 114, 114, 117, 114, 115, 114, 114, 115, 115, 115, 117, 114, 114
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "spawn",
          type = "",
          shape = "point",
          x = 920,
          y = 920,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "center",
          type = "",
          shape = "point",
          x = 360,
          y = 520,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "in_front",
          type = "",
          shape = "point",
          x = 360,
          y = 420,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 162,
          name = "toggle",
          type = "",
          shape = "point",
          x = 850,
          y = 830,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "barn_opened",
            ["inverted"] = false,
            ["target1"] = { id = 161 },
            ["target2"] = { id = 160 },
            ["target3"] = { id = 164 }
          }
        },
        {
          id = 163,
          name = "toggle",
          type = "",
          shape = "point",
          x = 850,
          y = 930,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "barn_opened",
            ["inverted"] = true,
            ["target1"] = { id = 1 }
          }
        }
      }
    }
  }
}
