return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 58,
  backgroundcolor = { 0, 0, 0 },
  properties = {
    ["light"] = true
  },
  tilesets = {
    {
      name = "rural",
      firstgid = 1,
      filename = "../../tilesets/rural.tsx",
      exportfilename = "../../tilesets/rural.lua"
    },
    {
      name = "rural_buildings",
      firstgid = 101,
      filename = "../../tilesets/rural_buildings.tsx",
      exportfilename = "../../tilesets/rural_buildings.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 45, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 46, 0, 0,
        0, 0, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 0, 0,
        0, 0, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 0, 0,
        0, 0, 61, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 62, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 160,
          width = 80,
          height = 120,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 130,
          width = 260,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 123,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 240,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 240,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 320,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 320,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 320,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 400,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 400,
          width = 80,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 122,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 130,
          width = 260,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1_1"] = "* (Whiteboard.)",
            ["text1_2"] = "* (There never was much to say about this thing...)",
            ["text2_1"] = "* (Not much to say about this thing.)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 120,
          width = 40,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 440,
          width = 560,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 120,
          width = 40,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 120,
          width = 480,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 190,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 190,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 190,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 270,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 270,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 270,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 350,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 350,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 350,
          width = 80,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 7,
          name = "spawn",
          type = "",
          shape = "point",
          x = 130,
          y = 230,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
