return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 20,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 79,
  properties = {
    ["music"] = "field_jarona",
    ["name"] = "Wheat Field - Start"
  },
  tilesets = {
    {
      name = "farm_world",
      firstgid = 1,
      filename = "../../../tilesets/farm_world.tsx",
      exportfilename = "../../../tilesets/farm_world.lua"
    },
    {
      name = "farm_world_extras",
      firstgid = 101,
      filename = "../../../tilesets/farm_world_extras.tsx",
      exportfilename = "../../../tilesets/farm_world_extras.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 105, 105, 104, 103, 104, 105, 104, 102, 0, 0, 0, 0, 0, 0, 0, 0, 12, 21, 5, 5, 5, 21, 103, 4, 101, 103, 102, 105,
        0, 0, 1, 13, 4, 13, 14, 11, 12, 11, 4, 0, 106, 0, 0, 0, 0, 0, 12, 21, 5, 5, 5, 21, 102, 102, 14, 101, 103, 0,
        0, 3, 11, 21, 21, 21, 21, 21, 21, 21, 21, 21, 12, 21, 12, 12, 0, 0, 21, 21, 5, 5, 5, 21, 101, 101, 103, 0, 12, 0,
        0, 2, 21, 21, 15, 15, 15, 15, 15, 15, 21, 21, 21, 21, 21, 12, 21, 21, 21, 21, 5, 5, 5, 21, 21, 21, 21, 101, 14, 0,
        0, 13, 21, 15, 15, 15, 15, 15, 15, 5, 5, 21, 21, 21, 21, 21, 21, 21, 5, 5, 5, 5, 5, 5, 5, 5, 21, 101, 0, 14,
        104, 1, 21, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 22, 105, 12,
        14, 22, 21, 5, 15, 15, 15, 15, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 22, 101, 2,
        22, 22, 5, 5, 5, 5, 5, 5, 5, 5, 5, 21, 21, 21, 21, 21, 5, 5, 5, 5, 5, 5, 15, 15, 15, 5, 5, 5, 102, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 21, 13, 1, 1, 2, 21, 21, 5, 5, 15, 15, 15, 15, 15, 15, 15, 15, 15, 103, 104,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 21, 1, 1, 0, 0, 0, 12, 22, 5, 5, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 22, 13, 14, 103, 102, 4, 3, 22, 5, 5, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 21, 13, 1, 2, 2, 22, 21, 5, 5, 5, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 21, 21, 21, 22, 5, 5, 5, 5, 5, 5, 15, 15, 15, 15, 15, 15, 21, 0, 0,
        15, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 15, 15, 21, 22, 0, 14,
        16, 15, 5, 5, 21, 21, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 22, 21, 0, 0, 11,
        0, 15, 15, 6, 22, 22, 6, 7, 21, 22, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 21, 22, 0, 0, 1, 104,
        0, 15, 16, 16, 21, 21, 0, 2, 22, 22, 21, 21, 21, 21, 5, 5, 5, 5, 21, 21, 21, 21, 21, 22, 21, 0, 0, 13, 0, 0,
        0, 0, 16, 15, 21, 22, 0, 14, 22, 22, 21, 21, 21, 21, 21, 21, 21, 21, 22, 0, 0, 0, 21, 21, 21, 0, 12, 0, 0, 0,
        0, 0, 0, 0, 21, 22, 0, 14, 13, 21, 21, 21, 2, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0,
        0, 0, 0, 0, 22, 22, 0, 14, 12, 13, 21, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 640,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 760,
          width = 120.5,
          height = 39.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000.5,
          y = 760.25,
          width = 199,
          height = 39.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120.75,
          y = 719.75,
          width = 79.5,
          height = 39.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 720,
          width = 39.5005,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440.5,
          y = 0.5,
          width = 278.5,
          height = 79,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640.25,
          y = 81,
          width = 78.4375,
          height = 39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1039.75,
          y = 0.166667,
          width = 159.833,
          height = 40.3333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080.1,
          y = 40.8333,
          width = 79.5,
          height = 39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 800.25,
          width = 480,
          height = 39.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 719.75,
          y = -41.75,
          width = 81.8337,
          height = 39.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 921.417,
          y = -40.75,
          width = 279.167,
          height = 39.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 360,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 400,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 440,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 40,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 600,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 680,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 720,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 320,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 0,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 80,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 120,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 200,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 520,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 560,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 600,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 640,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 680,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 760,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 720,
          width = 120,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 800,
          width = 320,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 680,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 720,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 11,
          name = "to_farm2",
          type = "",
          shape = "point",
          x = 200,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "to_farm4",
          type = "",
          shape = "point",
          x = 40,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "spawn",
          type = "",
          shape = "point",
          x = 200,
          y = 680,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "to_cornplate",
          type = "",
          shape = "point",
          x = 860,
          y = 40,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 451.667,
          width = 200,
          height = 120,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 844.583,
          y = 402.5,
          width = 185,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text1_1"] = "* (Humanity's greatest creation.)",
            ["text1_2"] = "* (The haybale.)",
            ["text2_1"] = "* (The haybale.)"
          }
        },
        {
          id = 7,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 160.045,
          y = 800.057,
          width = 79.9886,
          height = 40.9432,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm2",
            ["marker"] = "to_farm3"
          }
        },
        {
          id = 24,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 883.583,
          y = 360,
          width = 108.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybale",
            ["solid"] = false,
            ["text1_1"] = "* (?!)",
            ["text1_2"] = "* (Sticking out of the haybale was a Glowshard.)",
            ["text1_3"] = "* (You took[sound:item] the Glowshard.)"
          }
        },
        {
          id = 25,
          name = "enemy",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 120,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["chase"] = true,
            ["chasedist"] = 200,
            ["encounter"] = "colonel",
            ["enemy"] = "colonel",
            ["once"] = true
          }
        },
        {
          id = 29,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40.661,
          y = 240,
          width = 39.9886,
          height = 359.138,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm4",
            ["marker"] = "to_farm3sideexit"
          }
        },
        {
          id = 46,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "starwalker",
            ["text1_1"] = "* Hey,[wait:5] so,[wait:5] I'm a placeholder npc,[wait:5] but I heard that there's something cool in that haybale.",
            ["text2_1"] = "* Not this one.[wait:5] Thought I'd clarify a bit.",
            ["text3_1"] = "* Well,[wait:5] did you find it ??!?"
          }
        },
        {
          id = 47,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 360,
          width = 80,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1_1"] = "* Y'know,[wait:5] it's illegal around heres to rustle Jimmy's (!)",
            ["text2_1"] = "* STOP RUSTLING JIMMY'S (!!!)",
            ["text3_1"] = "* Why are you still rustling Jimmy.",
            ["text4_1"] = "* (You felt a shift in the quantum fluctuations of the wheat field.)",
            ["text4_2"] = "* (Things feel...[wait:5] a little emptier now.)",
            ["text5_1"] = "* (...)"
          }
        },
        {
          id = 48,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 660,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["heals"] = true,
            ["marker"] = "spawn",
            ["text1"] = "* (The thought of Grace in a vast field of wheat fills you with a certain power...)",
            ["text2"] = "* (The power of will.)",
            ["text3"] = "* (No,[wait:5] perhaps will isn't right.[wait:5] The power it fills you with...[wait:5] it is...)",
            ["text4"] = "* (The power[wait:20]\nof corn.)",
            ["text_once"] = true
          }
        },
        {
          id = 50,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 800,
          y = -40,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm5",
            ["marker"] = "entry"
          }
        },
        {
          id = 71,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 800,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/GONER_0",
            ["marker"] = "entry"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 720,
          width = 60,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 101,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 800,
          width = 60,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 101,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 72,
          name = "toggle",
          type = "",
          shape = "point",
          x = 720,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "GONER_0",
            ["inverted"] = true,
            ["target1"] = { id = 71 }
          }
        },
        {
          id = 75,
          name = "toggle",
          type = "",
          shape = "point",
          x = 920,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "GONER_0",
            ["inverted"] = false,
            ["target1"] = { id = 73 },
            ["target2"] = { id = 74 },
            ["target3"] = { id = 76 },
            ["target4"] = { id = 78 }
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 20,
      id = 2,
      name = "Camada de Blocos 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        105, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        111, 110, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105,
        103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 0, 103,
        101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 103,
        102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 103,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 104, 0,
        103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 105, 0, 0,
        104, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 103, 102, 0, 101, 105,
        104, 101, 0, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 0, 103, 0, 0, 0, 103, 0, 102, 104, 102,
        104, 104, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 108, 108, 0, 101, 104, 101, 102, 0, 0, 0, 102, 104,
        102, 103, 105, 102, 0, 0, 103, 0, 0, 0, 0, 0, 0, 104, 0, 101, 104, 105, 101, 112, 0, 105, 101, 103, 103, 104, 102, 104, 104, 102
      }
    }
  }
}
