return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 5,
  nextobjectid = 28,
  properties = {},
  tilesets = {
    {
      name = "farm_world",
      firstgid = 1,
      filename = "../../../tilesets/farm_world.tsx",
      exportfilename = "../../../tilesets/farm_world.lua"
    },
    {
      name = "farm_world_extras",
      firstgid = 101,
      filename = "../../../tilesets/farm_world_extras.tsx",
      exportfilename = "../../../tilesets/farm_world_extras.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 2, 21, 21, 21, 15,
        0, 0, 24, 24, 24, 4, 0, 0, 0, 2, 21, 21, 21, 21, 21, 21, 21, 21, 15, 15,
        0, 0, 24, 2, 13, 21, 21, 4, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        0, 24, 24, 2, 13, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        0, 24, 13, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        0, 24, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        24, 12, 13, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        24, 12, 12, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5,
        0, 2, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5,
        0, 0, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5,
        0, 0, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5,
        0, 12, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5,
        0, 2, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5,
        0, 0, 3, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5,
        0, 12, 3, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5,
        0, 1, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5,
        0, 14, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        0, 0, 13, 1, 21, 21, 21, 21, 15, 21, 21, 21, 15, 15, 15, 15, 15, 15, 21, 21,
        0, 0, 23, 14, 1, 14, 21, 21, 21, 21, 1, 21, 21, 21, 15, 15, 15, 21, 21, 23,
        0, 0, 0, 0, 0, 0, 3, 3, 3, 2, 0, 0, 0, 1, 21, 21, 21, 1, 1, 23
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 240,
          width = 200,
          height = 120,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 640,
          width = 319,
          height = 101,
          rotation = 0,
          opacity = 1,
          gid = 107,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 120,
          height = 160,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 402,
          y = 482,
          width = 120,
          height = 160,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 680,
          width = 120,
          height = 160,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 800.634,
          y = 1.695,
          width = 38.8977,
          height = 597.61,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm3",
            ["marker"] = "to_farm4"
          }
        },
        {
          id = 8,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 246.75,
          y = 273,
          width = 108.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took out some CandyCorn.)"
          }
        },
        {
          id = 9,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 486.75,
          y = 192,
          width = 190.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took out some CandyCorn.)"
          }
        },
        {
          id = 10,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 605.75,
          y = 637,
          width = 108.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took out some CandyCorn.)"
          }
        },
        {
          id = 11,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 407.75,
          y = 432,
          width = 106.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took out some CandyCorn.)"
          }
        },
        {
          id = 12,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 162.75,
          y = 598,
          width = 311.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybaleheal",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took out some CornMeal.)"
          }
        },
        {
          id = 13,
          name = "enemy",
          type = "",
          shape = "rectangle",
          x = 441.333,
          y = 394.167,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["chase"] = true,
            ["chasedist"] = 200,
            ["encounter"] = "colonel",
            ["enemy"] = "colonel"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1.2725,
          y = 2,
          width = 36.455,
          height = 797,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 41.7725,
          y = 0.5,
          width = 36.455,
          height = 239,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 82.7725,
          y = 0.5,
          width = 36.455,
          height = 159,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 121.772,
          y = 0.5,
          width = 74.455,
          height = 79,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 201.772,
          y = 1.5,
          width = 276.455,
          height = 39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240.772,
          y = 42.5,
          width = 121.455,
          height = 36,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 42.7725,
          y = 681.5,
          width = 36.455,
          height = 118,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 82.7725,
          y = 719,
          width = 36.455,
          height = 81,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40.7725,
          y = 359.5,
          width = 36.455,
          height = 81,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 41.7725,
          y = 521.5,
          width = 36.455,
          height = 39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 121.773,
          y = 760.5,
          width = 115.455,
          height = 39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 401.273,
          y = 760.5,
          width = 115.455,
          height = 39,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 759.773,
          y = 718.5,
          width = 36.455,
          height = 81,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "to_farm3sideexit",
          type = "",
          shape = "point",
          x = 778,
          y = 347,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
