return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 62,
  properties = {
    ["music"] = "field_jarona",
    ["name"] = "Wheat Field - Hay Room"
  },
  tilesets = {
    {
      name = "farm_world",
      firstgid = 1,
      filename = "../../../tilesets/farm_world.tsx",
      exportfilename = "../../../tilesets/farm_world.lua"
    },
    {
      name = "farm_world_extras",
      firstgid = 101,
      filename = "../../../tilesets/farm_world_extras.tsx",
      exportfilename = "../../../tilesets/farm_world_extras.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        104, 101, 103, 103, 104, 103, 103, 105, 104, 104, 105, 102, 2, 1, 1, 2, 14, 2, 0, 0,
        101, 102, 24, 102, 102, 4, 102, 102, 102, 2, 21, 21, 21, 21, 21, 21, 21, 21, 22, 0,
        102, 101, 101, 2, 13, 21, 21, 4, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 22, 0,
        0, 24, 104, 2, 13, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 21, 0,
        0, 104, 13, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 22, 0,
        0, 102, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 21, 0,
        24, 12, 13, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 22, 0,
        24, 12, 12, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 21,
        0, 2, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5,
        0, 103, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5,
        0, 103, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 15, 15,
        0, 12, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 6, 15, 15,
        0, 2, 2, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 5,
        0, 102, 3, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 5, 16,
        0, 12, 3, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 16, 15,
        0, 1, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 15,
        0, 14, 21, 21, 21, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        0, 0, 13, 1, 21, 21, 21, 21, 15, 21, 21, 21, 15, 15, 15, 15, 15, 15, 21, 21,
        0, 0, 0, 14, 1, 14, 21, 21, 21, 21, 1, 21, 21, 21, 15, 15, 15, 21, 21, 0,
        0, 0, 0, 0, 0, 0, 3, 3, 3, 2, 0, 0, 0, 1, 21, 21, 21, 1, 1, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 240,
          width = 200,
          height = 120,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 640,
          width = 319,
          height = 101,
          rotation = 0,
          opacity = 1,
          gid = 107,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 120,
          height = 160,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 402,
          y = 482,
          width = 120,
          height = 160,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 680,
          width = 120,
          height = 160,
          rotation = 0,
          opacity = 1,
          gid = 106,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 800.634,
          y = 280,
          width = 38.8977,
          height = 440,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm3",
            ["marker"] = "to_farm4"
          }
        },
        {
          id = 8,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 246.75,
          y = 273,
          width = 108.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took[sound:item] out some CandyCorn.)"
          }
        },
        {
          id = 9,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 486.75,
          y = 192,
          width = 190.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took[sound:item] out some CandyCorn.)"
          }
        },
        {
          id = 10,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 605.75,
          y = 637,
          width = 108.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took[sound:item] out some CandyCorn.)"
          }
        },
        {
          id = 11,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 407.75,
          y = 432,
          width = 106.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybalecandy",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took[sound:item] out some CandyCorn.)"
          }
        },
        {
          id = 12,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 162.75,
          y = 598,
          width = 311.5,
          height = 42,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["once"] = true,
            ["script"] = "behindhaybaleheal",
            ["solid"] = true,
            ["text1"] = "* (You stuck your hand in and took[sound:item] out some CornMeal.)"
          }
        },
        {
          id = 13,
          name = "enemy",
          type = "",
          shape = "rectangle",
          x = 441.333,
          y = 394.167,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["chase"] = true,
            ["chasedist"] = 200,
            ["encounter"] = "colonel",
            ["enemy"] = "colonel",
            ["once"] = true
          }
        },
        {
          id = 60,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 480,
          y = -40,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm4_revivemint",
            ["marker"] = "entry"
          }
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 5,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 105,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 102,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101,
        102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101,
        103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 103,
        101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104,
        101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 103,
        104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        105, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        103, 104, 103, 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        101, 102, 102, 102, 102, 104, 101, 101, 105, 101, 103, 102, 104, 104, 0, 0, 0, 105, 103, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 760,
          width = 240,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 720,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 520,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 520,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 360,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 200,
          width = 40,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 160,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 80,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 40,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 0,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 40,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 0,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 760,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 720,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 800,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 800,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 800,
          width = 160,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 0,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 40,
          width = 40,
          height = 240,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 14,
          name = "to_farm3sideexit",
          type = "",
          shape = "point",
          x = 760,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "to_mint",
          type = "",
          shape = "point",
          x = 600,
          y = 40,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
