return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 11,
  nextobjectid = 39,
  properties = {
    ["music"] = "garden",
    ["name"] = "Garden - Cave Entrance"
  },
  tilesets = {
    {
      name = "garden",
      firstgid = 1,
      filename = "../../../tilesets/garden.tsx"
    },
    {
      name = "garden_extras",
      firstgid = 101,
      filename = "../../../tilesets/garden_extras.tsx",
      exportfilename = "../../../tilesets/garden_extras.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 10,
      name = "star",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 0.5,
      parallaxy = 0.5,
      properties = {},
      encoding = "lua",
      data = {
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 12, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 12, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 14, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        13, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 12, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 13, 3, 3, 3, 3, 3, 3, 3, 4,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3,
        3, 3, 13, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 13, 3, 3, 3, 3, 3, 3, 13, 3, 3, 3, 3, 13, 3, 3, 14, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 5, 5, 5, 5, 5, 5, 5, 23, 23, 23, 23, 5, 5, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 5, 23, 23, 23, 23, 23, 23, 5, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 23, 24, 23, 23, 23, 23, 23, 23, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 23, 23, 23, 23, 23, 23, 24, 23, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 23, 23, 23, 23, 23, 23, 23, 5, 5, 5, 5, 5, 5, 0,
        0, 9, 5, 5, 5, 5, 5, 24, 23, 23, 23, 24, 23, 5, 5, 5, 5, 5, 9, 0,
        0, 19, 5, 5, 5, 5, 5, 5, 23, 5, 23, 23, 5, 5, 5, 5, 5, 5, 19, 0,
        0, 29, 9, 5, 5, 5, 5, 5, 5, 23, 24, 5, 5, 5, 5, 5, 5, 9, 29, 0,
        0, 39, 19, 9, 5, 5, 5, 5, 5, 5, 23, 5, 5, 5, 5, 5, 9, 19, 39, 0,
        0, 49, 29, 19, 9, 5, 5, 5, 5, 23, 5, 5, 5, 5, 5, 9, 19, 29, 49, 0,
        0, 59, 39, 29, 19, 9, 9, 5, 5, 23, 23, 5, 5, 9, 9, 19, 29, 39, 59, 0,
        0, 0, 49, 39, 29, 19, 19, 9, 9, 23, 5, 9, 9, 19, 19, 29, 39, 49, 0, 0,
        0, 0, 59, 49, 39, 29, 29, 19, 19, 5, 5, 19, 19, 29, 29, 39, 49, 59, 0, 0,
        0, 0, 0, 59, 49, 39, 39, 29, 29, 5, 5, 29, 29, 39, 39, 49, 59, 0, 0, 0,
        0, 0, 0, 0, 59, 49, 49, 39, 39, 5, 5, 39, 39, 49, 49, 59, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 59, 59, 49, 49, 5, 5, 49, 49, 59, 59, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 59, 59, 5, 5, 59, 59, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = -40,
          width = 558.667,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 119.333,
          width = 40.667,
          height = 240.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 40.6667,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = -7.10543e-15,
          width = 40.667,
          height = 40.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 0,
          width = 40.667,
          height = 40.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 40,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 120,
          width = 40.667,
          height = 240.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 360,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 440,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 480,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 520,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520.333,
          y = 560.667,
          width = 78.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 600,
          width = 78.667,
          height = 221.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 600,
          width = 78.667,
          height = 218.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 560,
          width = 78.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 480,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 520,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 440,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 360,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "spawn",
          type = "",
          shape = "point",
          x = 400,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "to_orchard",
          type = "",
          shape = "point",
          x = 400,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "kipkip",
            ["text1_1"] = "* (Welcome to the Cave Zone!)",
            ["text1_10"] = "* (So,[wait:5] it's tricky.[wait:5] But I think it could be worth your while...!)",
            ["text1_2"] = "* (Up ahead is a cave you can go into to find treasures galore!)",
            ["text1_3"] = "* (Be warned though --[wait:5] it is quite dangerous,[wait:5] and there are some things to consider.)",
            ["text1_4"] = "* (The cave consists of 5 SUBLEVELS.[wait:5] Each SUBLEVEL has [color:yellow]TREASURE [color:reset]and enemies.)",
            ["text1_5"] = "* (You must bring the [color:yellow]TREASURE[color:reset] one at a time to me at the SUBLEVEL's starting zone.)",
            ["text1_6"] = "* (Then,[wait:5] the entrance to the next SUBLEVEL opens.)",
            ["text1_7"] = "* (Once you enter the cave,[wait:5] you cannot leave until you reach the EXIT at the end...)",
            ["text1_8"] = "* (No healing items can be found in the cave...[wait:5] only what you come in with.)",
            ["text1_9"] = "* (If you are DEFEATED,[wait:5] you'll go back to the starting zone of the SUBLEVEL.)"
          }
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 402.5,
          width = 354.667,
          height = 266,
          rotation = 0,
          opacity = 1,
          gid = 138,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 195.833,
          width = 185.333,
          height = 103.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.cave_entrance",
            ["solid"] = true
          }
        },
        {
          id = 30,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["heals"] = true,
            ["marker"] = "spawn",
            ["text1"] = "* (A cave full of danger and glory awaits...)",
            ["text2"] = "* (You are filled with the power of spelunking.)",
            ["text_once"] = true
          }
        },
        {
          id = 32,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "kipkip",
            ["text1_1"] = "* (Welcome back!)",
            ["text1_2"] = "* (Yeah the cave closed in on itself as we left)",
            ["text1_3"] = "* (No clue why it did that,[wait:5] never seen that happen before in my entire caving career)",
            ["text1_4"] = "* (Might have something to do with The Key...)",
            ["text1_5"] = "* (But that's all for this zone.[wait:5] And don't worry, you got the money already.)",
            ["text2_1"] = "* (Huh?[wait:5] You think that cave was brutal and unfair and had bad level design?)",
            ["text2_2"] = "* (Heh.[sound:farmerlaugh][wait:5] You don't even know the half of it.)",
            ["text2_3"] = "* (Come back when you've finished Kipkip 2.[wait:5] There you'll see some REAL Lands of Torture.)",
            ["text3_1"] = "* (Good job in that cave.[wait:5] Usually we don't like foreigners but you're one of the good ones)",
            ["text3_2"] = "* (Yeah we're lowkey crazy jingoist i'll admit.[wait:5] And super $$$$ing greedy)",
            ["text3_3"] = "* (At least we're all the same color so nothing bad really happens with us as a whole)",
            ["text4_1"] = "* (Except for those shamans though. They think they're $$$$ing above everyone)",
            ["text4_2"] = "* (Just because you don't desire anything doesn't mean you're better than everyone else)",
            ["text5_1"] = "* (Like that $#!! can't be good for you your skin is orange and your leaf is on fire)",
            ["text5_2"] = "* (Like what are you doing.[wait:5] That isn't normal)",
            ["text6_1"] = "* (I'd really hate to see what would happen if some of them decided to join the GARDNER.)",
            ["text6_2"] = "* (With their superiority complex and their crazy power?[wait:5] PLUS the GARDNER's powers?)",
            ["text6_3"] = "* (...[wait:5]you're going up against the GARDNER,[wait:5] right?)",
            ["text6_4"] = "* (...Good luck.)",
            ["text7_1"] = "* (...Good luck.)"
          }
        },
        {
          id = 36,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["heals"] = true,
            ["marker"] = "spawn",
            ["text1"] = "* (And so,[wait:5] your spelunking adventure has ended.)",
            ["text2"] = "* (You are filled with the power of trauma.)",
            ["text_once"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 37,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 800,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/garden_orchard_pre",
            ["marker"] = "to_cave"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 33,
          name = "toggle",
          type = "",
          shape = "point",
          x = 852,
          y = 57,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "finishedFlowerDen",
            ["inverted"] = false,
            ["target1"] = { id = 32 },
            ["target2"] = { id = 36 }
          }
        },
        {
          id = 34,
          name = "toggle",
          type = "",
          shape = "point",
          x = 865,
          y = 97,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "finishedFlowerDen",
            ["inverted"] = true,
            ["target1"] = { id = 1 },
            ["target2"] = { id = 30 }
          }
        },
        {
          id = 35,
          name = "toggle",
          type = "",
          shape = "point",
          x = 897,
          y = 165,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "finishedFlowerDen",
            ["inverted"] = true,
            ["target1"] = { id = 2 },
            ["target2"] = { id = 3 }
          }
        }
      }
    }
  }
}
