return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 8,
  nextobjectid = 32,
  properties = {
    ["name"] = "Garden - Cave Entrance"
  },
  tilesets = {
    {
      name = "garden",
      firstgid = 1,
      filename = "../../../tilesets/garden.tsx"
    },
    {
      name = "garden_extras",
      firstgid = 101,
      filename = "../../../tilesets/garden_extras.tsx",
      exportfilename = "../../../tilesets/garden_extras.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0,
        0, 5, 5, 5, 5, 5, 5, 5, 23, 23, 23, 23, 5, 5, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 5, 23, 23, 23, 23, 23, 23, 5, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 23, 24, 23, 23, 23, 23, 23, 23, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 23, 23, 23, 23, 16, 23, 24, 23, 5, 5, 5, 5, 5, 0,
        0, 5, 5, 5, 5, 5, 23, 23, 23, 23, 23, 23, 23, 5, 5, 5, 5, 5, 5, 0,
        0, 9, 5, 5, 5, 5, 5, 24, 23, 23, 23, 24, 23, 5, 5, 5, 5, 5, 9, 0,
        0, 19, 5, 5, 5, 5, 5, 5, 23, 5, 23, 23, 5, 5, 5, 5, 5, 5, 19, 0,
        0, 29, 9, 5, 5, 5, 5, 5, 5, 23, 24, 5, 5, 5, 5, 5, 5, 9, 29, 0,
        0, 39, 19, 9, 5, 5, 5, 5, 5, 5, 23, 5, 5, 5, 5, 5, 9, 19, 39, 0,
        0, 49, 29, 19, 9, 5, 5, 5, 5, 23, 5, 5, 5, 5, 5, 9, 19, 29, 49, 0,
        0, 59, 39, 29, 19, 9, 9, 5, 5, 23, 23, 5, 5, 9, 9, 19, 29, 39, 59, 0,
        0, 0, 49, 39, 29, 19, 19, 9, 9, 23, 5, 9, 9, 19, 19, 29, 39, 49, 0, 0,
        0, 0, 59, 49, 39, 29, 29, 19, 19, 5, 5, 19, 19, 29, 29, 39, 49, 59, 0, 0,
        0, 0, 0, 59, 49, 39, 39, 29, 29, 5, 5, 29, 29, 39, 39, 49, 59, 0, 0, 0,
        0, 0, 0, 0, 59, 49, 49, 39, 39, 5, 5, 39, 39, 49, 49, 59, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 59, 59, 49, 49, 5, 5, 49, 49, 59, 59, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 59, 59, 5, 5, 59, 59, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = -40,
          width = 558.667,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 119.333,
          width = 40.667,
          height = 240.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 40.6667,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = -7.10543e-15,
          width = 40.667,
          height = 40.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 0,
          width = 40.667,
          height = 40.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 40,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 120,
          width = 40.667,
          height = 240.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 360,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 440,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 480,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 520,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520.333,
          y = 560.667,
          width = 78.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 600,
          width = 78.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 600,
          width = 78.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 560,
          width = 78.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 480,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 520,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 440,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 360,
          width = 40.667,
          height = 80.0003,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "kipkip",
            ["text1_1"] = "* (Welcome to the Cave Zone!)",
            ["text1_10"] = "* (So,[wait:5] it's tricky.[wait:5] But I think it could be worth your while...!)",
            ["text1_2"] = "* (Up ahead is a cave you can go into to find treasures galore!)",
            ["text1_3"] = "* (Be warned though --[wait:5] it is quite dangerous,[wait:5] and there are some things to consider.)",
            ["text1_4"] = "* (The cave consists of 5 SUBLEVELS.[wait:5] Each SUBLEVEL has [color:yellow]TREASURE [color:reset]and enemies.)",
            ["text1_5"] = "* (You must bring the [color:yellow]TREASURE[color:reset] one at a time to me at the SUBLEVEL's starting zone.)",
            ["text1_6"] = "* (Then,[wait:5] the entrance to the next SUBLEVEL opens.)",
            ["text1_7"] = "* (Once you enter the cave,[wait:5] you cannot leave until you reach the EXIT at the end...)",
            ["text1_8"] = "* (No healing items can be found in the cave...[wait:5] only what you come in with.)",
            ["text1_9"] = "* (If you are DEFEATED,[wait:5] you'll end up back here with your progress lost...)"
          }
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 402.5,
          width = 354.667,
          height = 266,
          rotation = 0,
          opacity = 1,
          gid = 138,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 195.833,
          width = 185.333,
          height = 103.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.cave_entrance",
            ["solid"] = true
          }
        },
        {
          id = 30,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["heals"] = true,
            ["marker"] = "spawn",
            ["text1"] = "* (A cave full of danger and glory awaits...)",
            ["text2"] = "* (You are filled with the power of spelunking.)",
            ["text_once"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "spawn",
          type = "",
          shape = "point",
          x = 400,
          y = 480,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    }
  }
}
