return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 40,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 7,
  nextobjectid = 81,
  properties = {
    ["music"] = "garden",
    ["name"] = "Garden - Weight Puzzle 2"
  },
  tilesets = {
    {
      name = "garden",
      firstgid = 1,
      filename = "../../../tilesets/garden.tsx"
    },
    {
      name = "garden_extras",
      firstgid = 101,
      filename = "../../../tilesets/garden_extras.tsx",
      exportfilename = "../../../tilesets/garden_extras.lua"
    },
    {
      name = "treasures",
      firstgid = 150,
      filename = "../../../tilesets/treasures.tsx",
      exportfilename = "../../../tilesets/treasures.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 40,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 48, 47, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        9, 9, 9, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 48, 48, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        19, 19, 19, 19, 5, 5, 5, 6, 6, 7, 5, 5, 5, 5, 5, 48, 47, 15, 15, 15, 15, 0, 0, 0, 48, 48, 48, 48, 0, 0,
        29, 29, 29, 5, 5, 5, 5, 5, 6, 7, 5, 5, 5, 5, 5, 48, 48, 15, 15, 15, 15, 15, 15, 48, 48, 48, 48, 48, 48, 0,
        39, 39, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 48, 48, 15, 15, 16, 16, 15, 15, 15, 48, 48, 48, 47, 48, 0,
        49, 49, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 48, 48, 15, 15, 16, 15, 15, 15, 15, 15, 15, 48, 48, 48, 0,
        59, 59, 19, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 47, 48, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 0,
        0, 0, 29, 19, 9, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 48, 48, 37, 37, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 0,
        0, 0, 39, 29, 19, 19, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 19, 19, 48, 48, 48, 15, 15, 15, 15, 15, 15, 15, 0,
        0, 0, 49, 39, 29, 29, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 29, 29, 48, 48, 48, 48, 15, 15, 15, 16, 15, 15, 0,
        0, 0, 59, 49, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 39, 39, 48, 48, 48, 48, 15, 15, 15, 16, 16, 15, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 7, 5, 49, 49, 0, 48, 48, 15, 15, 15, 15, 15, 15, 15, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 59, 59, 0, 15, 15, 15, 15, 15, 15, 15, 15, 15, 0,
        0, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 15, 15, 15, 15, 15, 15, 15, 15, 37, 37, 0,
        0, 5, 5, 5, 5, 7, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 15, 15, 15, 16, 15, 15, 15, 15, 15, 37, 19, 19, 0,
        0, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 15, 16, 15, 15, 15, 15, 15, 15, 38, 19, 29, 29, 0,
        0, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 15, 15, 15, 15, 15, 15, 15, 15, 19, 29, 39, 39, 0,
        0, 19, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 15, 15, 15, 15, 15, 15, 15, 37, 29, 39, 49, 49, 0,
        0, 29, 19, 9, 9, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 9, 9, 37, 37, 37, 38, 37, 37, 37, 19, 39, 49, 59, 59, 0,
        0, 39, 29, 19, 19, 19, 5, 5, 5, 5, 5, 5, 5, 5, 5, 19, 19, 19, 19, 19, 19, 19, 19, 19, 29, 49, 59, 0, 0, 0,
        0, 49, 39, 29, 29, 29, 5, 5, 5, 5, 5, 5, 5, 5, 5, 29, 29, 29, 29, 29, 29, 29, 29, 29, 39, 59, 0, 0, 0, 0,
        0, 59, 49, 39, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 39, 39, 39, 39, 39, 39, 39, 49, 0, 0, 0, 0, 0,
        0, 0, 59, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 49, 49, 49, 49, 49, 49, 49, 59, 0, 0, 0, 0, 0,
        0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 6, 5, 59, 59, 59, 59, 59, 59, 59, 0, 0, 0, 0, 0, 0,
        0, 0, 5, 5, 5, 5, 7, 6, 6, 5, 5, 5, 5, 6, 7, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 9, 9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 19, 19, 9, 9, 9, 9, 5, 5, 5, 5, 5, 5, 9, 9, 9, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 29, 29, 19, 19, 19, 19, 9, 9, 9, 5, 5, 9, 19, 19, 19, 29, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 39, 39, 29, 29, 29, 29, 19, 19, 19, 9, 9, 19, 29, 29, 29, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 49, 49, 39, 39, 39, 39, 29, 29, 29, 19, 19, 29, 39, 39, 39, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 59, 59, 49, 49, 49, 49, 39, 39, 39, 29, 29, 39, 49, 49, 49, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 59, 59, 59, 59, 49, 49, 49, 39, 39, 49, 59, 59, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 59, 59, 59, 49, 49, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "to_treasure",
          type = "",
          shape = "point",
          x = 49.3333,
          y = 162.667,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1240,
          width = 141.59,
          height = 230.163,
          rotation = 0,
          opacity = 1,
          gid = 161,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 120,
          width = 40,
          height = 80.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/garden_treasurehunt",
            ["marker"] = "to_weight2"
          }
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 560,
          width = 354,
          height = 205,
          rotation = 0,
          opacity = 1,
          gid = 148,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 1000,
          width = 354,
          height = 205,
          rotation = 0,
          opacity = 1,
          gid = 148,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 350,
          width = 358.666,
          height = 206.167,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.secondPaperBag",
            ["solid"] = true
          }
        },
        {
          id = 8,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 788,
          width = 358.666,
          height = 211.167,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.thirdPaperBag",
            ["solid"] = true
          }
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 360,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 149,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 320,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.pickupWeight",
            ["setflag"] = "weight99",
            ["solid"] = true
          }
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 440,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 149,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.pickupWeight",
            ["setflag"] = "weight98",
            ["solid"] = true
          }
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 440,
          width = 40,
          height = 60,
          rotation = 0,
          opacity = 1,
          gid = 149,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 400,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.pickupWeight",
            ["setflag"] = "weight97",
            ["solid"] = true
          }
        },
        {
          id = 23,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 319.667,
          y = 1011.42,
          width = 132.666,
          height = 222.167,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/treasures.pickupDyedScam",
            ["solid"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collisions",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 120.667,
          width = 79.5,
          height = 397.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = -80,
          width = 80.5,
          height = 397.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = -40,
          width = 170.5,
          height = 397.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 360,
          width = 39.5,
          height = 314.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 680,
          width = 118.5,
          height = 314.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 880,
          width = 239.5,
          height = 314.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 840,
          width = 39.5,
          height = 314.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 760,
          width = 39.5,
          height = 314.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 720,
          width = 39.5,
          height = 314.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 880,
          width = 39.5,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 880,
          width = 79.5,
          height = 78.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 43,
          y = 880,
          width = 196.5,
          height = 78.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 39,
          y = 800,
          width = 41.8333,
          height = 78.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 839.333,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 123.583,
          y = 399.666,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 360,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 440,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 440,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 240,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 280,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 320,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 200,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 200,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 200,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 200,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 201.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 191,
          y = 40,
          width = 250.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 0,
          width = 201.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 40,
          width = 201.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 80,
          width = 201.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 120,
          width = 201.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 160,
          width = 201.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 200,
          width = 79.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 240,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 480,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 480,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 74,
          y = 520,
          width = 85.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 560,
          width = 41.8333,
          height = 78.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 640,
          width = 41.8333,
          height = 202.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 440,
          width = 39.5,
          height = 239.334,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 440,
          width = 39.5,
          height = 238.334,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 760,
          y = 440,
          width = 39.5,
          height = 198.334,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 439.5,
          width = 39.5,
          height = 159.834,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 440,
          width = 39.5,
          height = 159.834,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 480.5,
          width = 39.5,
          height = 79.334,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1160,
          width = 39.5,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 1240,
          width = 39.5,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 1200,
          width = 120.833,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 1280,
          width = 80.8333,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1240,
          width = 120.833,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1200,
          width = 159.5,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 1160,
          width = 80.8333,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1000,
          width = 80.8333,
          height = 199.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 960,
          width = 41.8333,
          height = 78.667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 960,
          width = 39.5,
          height = 39.3337,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 17,
          name = "toggle",
          type = "",
          shape = "point",
          x = 887,
          y = 99,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "weight99",
            ["inverted"] = true,
            ["target1"] = { id = 9 },
            ["target2"] = { id = 10 }
          }
        },
        {
          id = 18,
          name = "toggle",
          type = "",
          shape = "point",
          x = 997,
          y = 91,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "weight98",
            ["inverted"] = true,
            ["target1"] = { id = 11 },
            ["target2"] = { id = 12 }
          }
        },
        {
          id = 19,
          name = "toggle",
          type = "",
          shape = "point",
          x = 1097,
          y = 85,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "weight97",
            ["inverted"] = true,
            ["target1"] = { id = 13 },
            ["target2"] = { id = 14 }
          }
        },
        {
          id = 20,
          name = "toggle",
          type = "",
          shape = "point",
          x = 648,
          y = 481.333,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "secondPaperBag",
            ["inverted"] = true,
            ["target1"] = { id = 4 },
            ["target2"] = { id = 7 }
          }
        },
        {
          id = 21,
          name = "toggle",
          type = "",
          shape = "point",
          x = 710,
          y = 674,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "thirdPaperBag",
            ["inverted"] = true,
            ["target1"] = { id = 5 },
            ["target2"] = { id = 8 }
          }
        },
        {
          id = 80,
          name = "toggle",
          type = "",
          shape = "point",
          x = 904,
          y = 1316,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "pickedUpDyedScam",
            ["inverted"] = true,
            ["target1"] = { id = 22 },
            ["target2"] = { id = 23 }
          }
        }
      }
    }
  }
}
