return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 18,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 15,
  nextobjectid = 77,
  properties = {
    ["name"] = "Garden - 2nd \"Barracks\""
  },
  tilesets = {
    {
      name = "farm_world",
      firstgid = 1,
      filename = "../../../tilesets/farm_world.tsx",
      exportfilename = "../../../tilesets/farm_world.lua"
    },
    {
      name = "garden",
      firstgid = 101,
      filename = "../../../tilesets/garden.tsx"
    },
    {
      name = "farm_world_extras",
      firstgid = 201,
      filename = "../../../tilesets/farm_world_extras.tsx",
      exportfilename = "../../../tilesets/farm_world_extras.lua"
    },
    {
      name = "garden_extras",
      firstgid = 228,
      filename = "../../../tilesets/garden_extras.tsx",
      exportfilename = "../../../tilesets/garden_extras.lua"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "objects_midground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 0.75,
      properties = {},
      objects = {
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 410,
          y = 70,
          width = 86,
          height = 66,
          rotation = 0,
          opacity = 1,
          gid = 224,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "objects_foreground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 0.85,
      properties = {},
      objects = {
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 20,
          y = 90,
          width = 196,
          height = 186,
          rotation = 0,
          opacity = 1,
          gid = 220,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 18,
      id = 1,
      name = "Camada de Blocos 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 103, 103, 103, 103, 0, 0, 0, 103, 103, 103,
        0, 0, 0, 0, 0, 0, 103, 103, 103, 103, 0, 0, 0, 103, 103, 103,
        112, 0, 0, 0, 0, 0, 103, 103, 103, 103, 103, 103, 103, 103, 113, 103,
        103, 121, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 122, 112, 103,
        103, 105, 105, 105, 105, 105, 105, 105, 106, 105, 105, 105, 105, 105, 103, 102,
        103, 105, 105, 106, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 0, 0,
        103, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
        103, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
        103, 105, 105, 105, 105, 106, 105, 105, 105, 105, 106, 105, 105, 105, 109, 109,
        103, 105, 105, 105, 105, 105, 106, 105, 105, 105, 105, 105, 105, 106, 119, 119,
        103, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 125, 125,
        103, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 126, 126,
        103, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 135, 135,
        103, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 126, 136, 136,
        103, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 135, 0, 0,
        103, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 136, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 18,
      id = 5,
      name = "Camada de Blocos 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 257, 258, 260, 257, 259, 260, 257, 257, 259, 257, 259, 257, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 30, 30, 30, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 30, 30, 30, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 30, 30, 30, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 30, 30, 30, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 30, 30, 30, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "objects_camera",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 50,
          name = "cameratarget",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 640,
          height = 430,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["lockx"] = true,
            ["locky"] = true,
            ["marker"] = "camera",
            ["returnspeed"] = 12,
            ["speed"] = 8
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 280,
          width = 320,
          height = 80,
          rotation = 0,
          opacity = 1,
          gid = 214,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 620,
          width = 120,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/farm_climb",
            ["marker"] = "to_garden"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_ladder",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 32,
          name = "climbarea",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 120,
          height = 200,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 76 }
          }
        },
        {
          id = 41,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 46 }
          }
        },
        {
          id = 42,
          name = "climbexit",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 75 }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 43,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 40 }
          }
        },
        {
          id = 44,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 41 }
          }
        },
        {
          id = 45,
          name = "climbentry",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 440,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["target"] = { id = 42 }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "collision",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 240,
          width = 160,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 240,
          width = 80,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 120,
          width = 40,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 440,
          width = 520,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 120,
          width = 600,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 360,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 160,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 360,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 200,
          width = 260,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 18,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 200,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 19,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 240,
          width = 20,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 20,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 310,
          y = 240,
          width = 50,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 21,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 460,
          y = 200,
          width = 20,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["solid"] = true,
            ["text"] = "* (Green couch in the room.)"
          }
        },
        {
          id = 23,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["talk"] = true,
            ["talksprite"] = "talk",
            ["text1_1"] = "* Welcome to the SECOND BARRACKS room,[wait:5] soldier!",
            ["text1_2"] = "* Me and the company are waiting for orders,[wait:5] soldier!",
            ["text1_3"] = "* No PRISMS OF LIGHT here though,[wait:5] soldier.[wait:5] We don't have the funds for that",
            ["text1_4"] = "* That stuff is like crazy expensive dude.",
            ["text1_5"] = "* ...[wait:5]soldier.",
            ["text2_1"] = "* ...[wait:5]soldier."
          }
        },
        {
          id = 24,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["cutscene"] = "chapter1/garden.barracks2"
          }
        },
        {
          id = 25,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["solid"] = false,
            ["talk"] = true,
            ["talksprite"] = "talk",
            ["text1_1"] = "* The GARDEN is beautiful...",
            ["text1_2"] = "* That's what we named this door.[wait:5] \"The GARDEN.\"",
            ["text2_1"] = "* The GARDEN..."
          }
        },
        {
          id = 26,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 135.167,
          y = 240,
          width = 24.8333,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["solid"] = false,
            ["talk"] = true,
            ["talksprite"] = "talk",
            ["text1_1"] = "* Good evening,[wait:5] Master Warrant Officer."
          }
        },
        {
          id = 27,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "colonel",
            ["solid"] = true,
            ["talk"] = true,
            ["talksprite"] = "talk",
            ["text1_1"] = "* Hm?[wait:5] How did we get here first?",
            ["text1_2"] = "* Simple,[wait:5] major.[wait:10] Helicopter",
            ["text2_1"] = "* We could've provided air support while you were being chased but we got scared"
          }
        },
        {
          id = 38,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "chapter1/garden.barracks2_partydisband",
            ["once"] = false
          }
        },
        {
          id = 68,
          name = "warpdoor",
          type = "",
          shape = "point",
          x = 120,
          y = 160,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag1"] = "barracks",
            ["flag2"] = "gardner_chase_end",
            ["map1"] = "chapter1/farm_world/farm6_warpdoor",
            ["map2"] = "chapter1/farm_world/garden1",
            ["marker1"] = "warp",
            ["marker2"] = "warp",
            ["name1"] = "Wheat Field",
            ["name2"] = "Garden",
            ["openflag"] = "gardner_chase_end"
          }
        },
        {
          id = 72,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 240,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "chapter1/farm_world/garden2",
            ["marker"] = "to_garden1"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 33,
          name = "to_farm",
          type = "",
          shape = "point",
          x = 340,
          y = 600,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["player_state"] = "CLIMB"
          }
        },
        {
          id = 46,
          name = "climb_exit",
          type = "",
          shape = "point",
          x = 340,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "spawn",
          type = "",
          shape = "point",
          x = 340,
          y = 320,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "camera",
          type = "",
          shape = "point",
          x = 320,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "warp",
          type = "",
          shape = "point",
          x = 120,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "to_garden2",
          type = "",
          shape = "point",
          x = 600,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "climb_exit",
          type = "",
          shape = "point",
          x = 380,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "climb_exit",
          type = "",
          shape = "point",
          x = 300,
          y = 400,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 47,
          name = "toggle",
          type = "",
          shape = "point",
          x = 340,
          y = 57,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "leading_colonels_squad",
            ["inverted"] = true,
            ["target1"] = { id = 25 },
            ["target2"] = { id = 26 },
            ["target3"] = { id = 23 },
            ["target4"] = { id = 24 },
            ["target5"] = { id = 27 },
            ["target6"] = { id = 71 }
          }
        },
        {
          id = 49,
          name = "toggle",
          type = "",
          shape = "point",
          x = 515,
          y = 50,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "leading_colonels_squad",
            ["target"] = { id = 38 }
          }
        }
      }
    }
  }
}
